import io
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

def extract_text_from_docx(file_bytes: bytes) -> str:
    """Extract all text from .docx bytes, preserving structure."""
    doc = Document(io.BytesIO(file_bytes))
    parts = []
    for para in doc.paragraphs:
        if para.style.name.startswith("Heading"):
            level = para.style.name.replace("Heading ", "")
            prefix = "#" * int(level) if level.isdigit() else "##"
            parts.append(f"{prefix} {para.text}")
        else:
            parts.append(para.text)

    for i, table in enumerate(doc.tables):
        parts.append(f"\n[Table {i+1}]")
        for row in table.rows:
            cells = [cell.text.strip() for cell in row.cells]
            parts.append(" | ".join(cells))

    return "\n".join(parts)

def generate_docx_bytes(title: str, content: str, doc_type: str) -> io.BytesIO:
    """Generate a formatted .docx and return as BytesIO (in-memory, no file saved)."""
    doc = Document()

    # Title
    title_para = doc.add_heading(title, level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Metadata
    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = meta.add_run(f"Document Type: {doc_type.upper()} | Generated by Pipeline AI")
    run.font.size = Pt(9)
    run.font.color.rgb = RGBColor(0x6B, 0x72, 0x80)

    doc.add_paragraph()

    for line in content.split("\n"):
        line = line.strip()
        if not line:
            doc.add_paragraph()
            continue
        if line.startswith("### "):
            doc.add_heading(line[4:], level=3)
        elif line.startswith("## "):
            doc.add_heading(line[3:], level=2)
        elif line.startswith("# "):
            doc.add_heading(line[2:], level=1)
        elif line.startswith("- ") or line.startswith("* "):
            p = doc.add_paragraph(style="List Bullet")
            p.text = line[2:]
        else:
            doc.add_paragraph(line)

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf

def get_doc_type_label(doc_type: str) -> str:
    labels = {
        "pmp": "Project Management Plan",
        "requirements": "Requirements Document",
        "test_script": "Test Script",
        "deploy_plan": "Deployment Plan",
        "user_manual": "User Manual",
    }
    return labels.get(doc_type, doc_type.upper())
