import os
from pathlib import Path
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from app.config import settings

def extract_text_from_docx(filepath: str) -> str:
    """Extract all text from a .docx file preserving structure."""
    doc = Document(filepath)
    parts = []
    for para in doc.paragraphs:
        if para.style.name.startswith("Heading"):
            level = para.style.name.replace("Heading ", "")
            prefix = "#" * int(level) if level.isdigit() else "##"
            parts.append(f"{prefix} {para.text}")
        else:
            parts.append(para.text)

    # Extract tables
    for i, table in enumerate(doc.tables):
        parts.append(f"\n[Table {i+1}]")
        for row in table.rows:
            cells = [cell.text.strip() for cell in row.cells]
            parts.append(" | ".join(cells))

    return "\n".join(parts)

def generate_docx(title: str, content: str, doc_type: str) -> str:
    """Generate a formatted .docx file and return the file path."""
    doc = Document()

    # Title
    title_para = doc.add_heading(title, level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Metadata line
    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = meta.add_run(f"Document Type: {doc_type.upper()} | Generated by Pipeline AI")
    run.font.size = Pt(9)
    run.font.color.rgb = RGBColor(0x6B, 0x72, 0x80)

    doc.add_paragraph()  # spacer

    # Process content lines
    for line in content.split("\n"):
        line = line.strip()
        if not line:
            doc.add_paragraph()
            continue

        # Headings
        if line.startswith("### "):
            doc.add_heading(line[4:], level=3)
        elif line.startswith("## "):
            doc.add_heading(line[3:], level=2)
        elif line.startswith("# "):
            doc.add_heading(line[2:], level=1)
        elif line.startswith("- ") or line.startswith("* "):
            p = doc.add_paragraph(style="List Bullet")
            p.text = line[2:]
        elif line.startswith("| "):
            # Simple table row detection
            cells = [c.strip() for c in line.split("|") if c.strip()]
            if cells:
                p = doc.add_paragraph()
                p.text = "  ".join(cells)
                p.runs[0].font.size = Pt(9)
        elif line.startswith("[Table"):
            pass  # placeholder for future table support
        else:
            doc.add_paragraph(line)

    # Save
    filename = f"{doc_type}_{title.lower().replace(' ', '_')}_{Path(title).stem}.docx"
    filepath = os.path.join(settings.GENERATED_DIR, filename)
    doc.save(filepath)
    return filepath

def get_doc_type_label(doc_type: str) -> str:
    labels = {
        "pmp": "Project Management Plan",
        "requirements": "Requirements Document",
        "test_script": "Test Script",
        "deploy_plan": "Deployment Plan",
        "user_manual": "User Manual",
    }
    return labels.get(doc_type, doc_type.upper())
