from fastapi import APIRouter, Depends, HTTPException, UploadFile, File, Form
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from app.database import get_db
from app.models.project import Project
from app.models.document import Document, DocType
from app.schemas.document import DocumentResponse, DocumentGenerate
from app.services.document_processor import extract_text_from_docx, generate_docx_bytes, get_doc_type_label
from app.services.supabase_storage import upload_to_supabase, download_from_supabase

router = APIRouter(prefix="/api/projects/{project_id}/documents", tags=["Documents"])

@router.get("")
def list_documents(project_id: str, db: Session = Depends(get_db)):
    docs = db.query(Document).filter(Document.project_id == project_id).all()
    return [DocumentResponse.model_validate(d) for d in docs]

@router.post("/upload", status_code=201)
def upload_document(
    project_id: str,
    file: UploadFile = File(...),
    doc_type: str = Form("pmp"),
    db: Session = Depends(get_db),
):
    project = db.query(Project).filter(Project.id == project_id).first()
    if not project:
        raise HTTPException(404, "Project not found")

    if doc_type not in [t.value for t in DocType]:
        raise HTTPException(400, f"Invalid doc_type")

    file_bytes = file.file.read()

    content_text = ""
    if file.filename and file.filename.endswith(".docx"):
        try:
            content_text = extract_text_from_docx(file_bytes)
        except Exception as e:
            raise HTTPException(400, f"Failed to parse document: {str(e)}")
    else:
        content_text = f"[Uploaded: {file.filename}]"

    filename = f"{project_id}/{doc_type}_{file.filename}"
    try:
        import asyncio
        asyncio.run(upload_to_supabase(file_bytes, filename))
    except Exception:
        pass  # Supabase not configured

    doc = Document(
        project_id=project_id,
        doc_type=DocType(doc_type),
        title=file.filename or "untitled",
        filename=filename,
        original_filename=file.filename or "",
        content=content_text,
    )
    db.add(doc)
    db.commit()
    db.refresh(doc)
    return DocumentResponse.model_validate(doc)

@router.post("/generate")
def generate_document(
    project_id: str,
    data: DocumentGenerate,
    db: Session = Depends(get_db),
):
    project = db.query(Project).filter(Project.id == project_id).first()
    if not project:
        raise HTTPException(404, "Project not found")

    if data.doc_type not in [t.value for t in DocType]:
        raise HTTPException(400, f"Invalid doc_type")

    doc_label = get_doc_type_label(data.doc_type)
    title = data.title or f"{doc_label} - {project.name}"

    content = f"""# {title}

## Project: {project.name}
{project.description or 'No description provided.'}

## Document Type
{doc_label}

---

## 1. Project Overview
{project.description or 'No description provided.'}

## 2. Key Stakeholders
- Project Manager
- Project Team
- Client / Customer

## 3. Scope
This document covers the {doc_label.lower()} for {project.name}.

## 4. Timeline
- Status: Active
- Start: {project.created_at.strftime('%Y-%m-%d') if project.created_at else 'TBD'}

## 5. Deliverables
- {doc_label} document
- Supporting artifacts

---

*Generated by Pipeline AI — PMBOK-aligned document generation*
"""

    doc_bytes = generate_docx_bytes(title, content, data.doc_type)

    # Save metadata to DB
    doc = Document(
        project_id=project_id,
        doc_type=DocType(data.doc_type),
        title=title,
        filename="",
        original_filename=f"{data.doc_type}_{project.name}.docx",
        content=content,
    )
    db.add(doc)
    db.commit()

    filename = f"{data.doc_type}_{project.name.replace(' ', '_')}.docx"
    return StreamingResponse(
        doc_bytes,
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )

@router.get("/{doc_id}/download")
def download_document(project_id: str, doc_id: str, db: Session = Depends(get_db)):
    doc = db.query(Document).filter(Document.id == doc_id, Document.project_id == project_id).first()
    if not doc:
        raise HTTPException(404, "Document not found")

    if doc.filename:
        try:
            import asyncio
            file_bytes = asyncio.run(download_from_supabase(doc.filename))
            import io
            return StreamingResponse(
                io.BytesIO(file_bytes),
                media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                headers={"Content-Disposition": f'attachment; filename="{doc.original_filename}"'},
            )
        except Exception:
            pass

    # Fallback: regenerate from content
    buf = generate_docx_bytes(doc.title, doc.content or "", doc.doc_type.value if hasattr(doc.doc_type, 'value') else str(doc.doc_type))
    return StreamingResponse(
        buf,
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        headers={"Content-Disposition": f'attachment; filename="{doc.original_filename}"'},
    )
