import os
import shutil
from pathlib import Path
from fastapi import APIRouter, Depends, HTTPException, UploadFile, File, Form
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from app.database import get_db
from app.models.project import Project
from app.models.document import Document, DocType
from app.schemas.document import DocumentResponse, DocumentGenerate
from app.services.document_processor import extract_text_from_docx, generate_docx, get_doc_type_label
from app.config import settings

router = APIRouter(prefix="/api/projects/{project_id}/documents", tags=["Documents"])

@router.get("")
async def list_documents(project_id: str, db: AsyncSession = Depends(get_db)):
    result = await db.execute(select(Document).where(Document.project_id == project_id))
    docs = result.scalars().all()
    return [DocumentResponse.model_validate(d) for d in docs]

@router.post("/upload", status_code=201)
async def upload_document(
    project_id: str,
    file: UploadFile = File(...),
    doc_type: str = Form("pmp"),
    db: AsyncSession = Depends(get_db),
):
    # Verify project
    proj = await db.execute(select(Project).where(Project.id == project_id))
    if not proj.scalar_one_or_none():
        raise HTTPException(404, "Project not found")

    # Validate doc_type
    if doc_type not in [t.value for t in DocType]:
        raise HTTPException(400, f"Invalid doc_type. Must be one of: {[t.value for t in DocType]}")

    # Save uploaded file
    os.makedirs(settings.UPLOAD_DIR, exist_ok=True)
    filename = f"{doc_type}_{file.filename}"
    filepath = os.path.join(settings.UPLOAD_DIR, filename)
    with open(filepath, "wb") as f:
        content = await file.read()
        f.write(content)

    # Extract text from .docx
    content_text = ""
    if filename.endswith(".docx"):
        try:
            content_text = extract_text_from_docx(filepath)
        except Exception as e:
            raise HTTPException(400, f"Failed to parse document: {str(e)}")
    else:
        content_text = f"[Uploaded: {file.filename}]"

    # Save to database
    doc = Document(
        project_id=project_id,
        doc_type=DocType(doc_type),
        title=file.filename,
        filename=filename,
        original_filename=file.filename,
        content=content_text,
    )
    db.add(doc)
    await db.commit()
    await db.refresh(doc)
    return DocumentResponse.model_validate(doc)

@router.post("/generate", status_code=201)
async def generate_document(
    project_id: str,
    data: DocumentGenerate,
    db: AsyncSession = Depends(get_db),
):
    # Verify project
    proj_result = await db.execute(select(Project).where(Project.id == project_id))
    project = proj_result.scalar_one_or_none()
    if not project:
        raise HTTPException(404, "Project not found")

    # Validate doc_type
    if data.doc_type not in [t.value for t in DocType]:
        raise HTTPException(400, f"Invalid doc_type. Must be one of: {[t.value for t in DocType]}")

    # Generate document content based on project info and doc_type
    doc_label = get_doc_type_label(data.doc_type)
    title = data.title or f"{doc_label} - {project.name}"

    content = f"""# {title}

## Project: {project.name}
{project.description}

## Document Type
{doc_label}

---

## 1. Project Overview
{project.description}

## 2. Key Stakeholders
- Project Manager
- Project Team
- Client

## 3. Scope
This document covers the {doc_label.lower()} for {project.name}.

## 4. Timeline
- Start Date: {project.created_at.strftime('%Y-%m-%d') if project.created_at else 'TBD'}
- Status: {project.status.value if hasattr(project.status, 'value') else project.status}

## 5. Deliverables
- {doc_label} document
- Supporting artifacts

---

*Generated by Pipeline AI — PMBOK-aligned document generation*
"""

    # Generate .docx file
    os.makedirs(settings.GENERATED_DIR, exist_ok=True)
    filepath = generate_docx(title, content, data.doc_type)

    # Save to database
    doc = Document(
        project_id=project_id,
        doc_type=DocType(data.doc_type),
        title=title,
        filename=os.path.basename(filepath),
        original_filename=f"{data.doc_type}_{project.name}.docx",
        content=content,
    )
    db.add(doc)
    await db.commit()
    await db.refresh(doc)
    return DocumentResponse.model_validate(doc)

@router.get("/{doc_id}/download")
async def download_document(project_id: str, doc_id: str, db: AsyncSession = Depends(get_db)):
    result = await db.execute(select(Document).where(Document.id == doc_id, Document.project_id == project_id))
    doc = result.scalar_one_or_none()
    if not doc:
        raise HTTPException(404, "Document not found")

    from fastapi.responses import FileResponse
    filepath = os.path.join(settings.GENERATED_DIR, doc.filename)
    if not os.path.exists(filepath):
        # Try uploads dir
        filepath = os.path.join(settings.UPLOAD_DIR, doc.filename)
    if not os.path.exists(filepath):
        raise HTTPException(404, "File not found on disk")

    return FileResponse(filepath, filename=doc.original_filename or doc.filename)
